---
title: "Integración de los datos suplementarios de los grupos"
author: "Marius Bottin"
date: "`r Sys.Date()`"
output: 
    pdf_document:
       number_sections: true
       toc: true
       toc_depth: 4
       latex_engine: xelatex
---


************************

Se trata en este documento de añadir los datos que no hacen parte de las variables principales de la estructura general de la base de datos, por ejemplo:

* variables ambientales
* caracteristicas individuales de los individuos muestreados (formas de vida, sexo, edad etc)
* etc.


```{r setup}
knitr::opts_chunk$set(tidy.opts = list(width.cutoff = 70), tidy = TRUE, connection="fracking_db", max.print=100)
def.chunk.hook  <- knitr::knit_hooks$get("chunk")
knitr::knit_hooks$set(chunk = function(x, options) {
  x <- def.chunk.hook(x, options)
  paste0("\n \\", "footnotesize","\n\n", x, "\n\n \\normalsize\n\n")
})
require(openxlsx)
require(RPostgreSQL)

```

```{r}
fracking_db <- dbConnect(PostgreSQL(), dbname='fracking')
```









```{r}
dbDisconnect(fracking_db)
```

