---
title: "Estructura de muestreo de los grupos"
author: "Marius Bottin"
date: "`r Sys.Date()`"
output: 
    pdf_document:
       number_sections: true
       toc: true
       toc_depth: 4
       latex_engine: xelatex
---


************************

```{r setup}
knitr::opts_chunk$set(tidy.opts = list(width.cutoff = 70), tidy = TRUE, connection="fracking_db", max.print=100)
require(openxlsx)
require(RPostgreSQL)

```

```{r}
fracking_db <- dbConnect(PostgreSQL(), dbname='fracking')
```



# Insectos

## Mariposas

```{sql}
WITH a AS(
SELECT 
  event_id,
  REGEXP_REPLACE(event_id,'^ANH_([0-9]{1,3})_T\. Van Someren-Rydon([0-9])_(202[12]-[0-9][0-9]-[0-9][0-9])/(202[12]-[0-9][0-9]-[0-9][0-9])$','\1')::int anh_num,
  REGEXP_REPLACE(event_id,'^ANH_([0-9]{1,3})_T\. Van Someren-Rydon([0-9])_(202[12]-[0-9][0-9]-[0-9][0-9])/(202[12]-[0-9][0-9]-[0-9][0-9])$','\2')::int trap_num,
  REGEXP_REPLACE(event_id,'^ANH_([0-9]{1,3})_T\. Van Someren-Rydon([0-9])_(202[12]-[0-9][0-9]-[0-9][0-9])/(202[12]-[0-9][0-9]-[0-9][0-9])$','\3')::date fecha1,
  REGEXP_REPLACE(event_id,'^ANH_([0-9]{1,3})_T\. Van Someren-Rydon([0-9])_(202[12]-[0-9][0-9]-[0-9][0-9])/(202[12]-[0-9][0-9]-[0-9][0-9])$','\4')::date fecha2
FROM raw_dwc.mariposas_event
ORDER BY anh_num, fecha1, trap_num
)
SELECT anh_num, EXTRACT(YEAR FROM fecha1) "year",ARRAY_AGG(trap_num),count(*)
FROM a
GROUP BY anh_num ,EXTRACT(YEAR FROM fecha1)
ORDER BY anh_num, EXTRACT(YEAR FROM fecha1),count(*)
```

## Escarabajos

```{sql}
WITH a AS(
SELECT event_id,
  REGEXP_REPLACE(event_id,'^ANH_([0-9]{1,3}).*$','\1')::int anh_num,
  CASE
     WHEN event_id ~ '^ANH_[0-9]{1,3}_Captura manual[0-9]_202[12]-[0-9]{2}-[0-9]{2}$' THEN 'Captura manual'
     WHEN event_id ~ '^ANH_[0-9]{1,3}_T. Exc. Human[0-9]_202[12]-[0-9]{2}-[0-9]{2}/202[12]-[0-9]{2}-[0-9]{2}$' THEN 'Tramp Exc'
  END metodo,
  CASE
     WHEN event_id ~ '^ANH_[0-9]{1,3}_Captura manual[0-9]_202[12]-[0-9]{2}-[0-9]{2}$' THEN REGEXP_REPLACE(event_id,'^ANH_[0-9]{1,3}_Captura manual([0-9])_202[12]-[0-9]{2}-[0-9]{2}$','\1')::int
     WHEN event_id ~ '^ANH_[0-9]{1,3}_T. Exc. Human[0-9]_202[12]-[0-9]{2}-[0-9]{2}/202[12]-[0-9]{2}-[0-9]{2}$' THEN REGEXP_REPLACE(event_id,'^ANH_[0-9]{1,3}_T. Exc. Human([0-9])_202[12]-[0-9]{2}-[0-9]{2}/202[12]-[0-9]{2}-[0-9]{2}$','\1')::int
  END trap_num,
  CASE
     WHEN event_id ~ '^ANH_[0-9]{1,3}_Captura manual[0-9]_202[12]-[0-9]{2}-[0-9]{2}$' THEN REGEXP_REPLACE(event_id,'^ANH_[0-9]{1,3}_Captura manual[0-9]_(202[12])-[0-9]{2}-[0-9]{2}$','\1')
     WHEN event_id ~ '^ANH_[0-9]{1,3}_T. Exc. Human[0-9]_202[12]-[0-9]{2}-[0-9]{2}/202[12]-[0-9]{2}-[0-9]{2}$' THEN REGEXP_REPLACE(event_id,'^ANH_[0-9]{1,3}_T. Exc. Human[0-9]_(202[12])-[0-9]{2}-[0-9]{2}/202[12]-[0-9]{2}-[0-9]{2}$','\1')
  END "year"
FROM raw_dwc.escarabajos_event
)
SELECT anh_num,"year",metodo,ARRAY_AGG(trap_num ORDER BY trap_num) traps
FROM a
GROUP BY anh_num,"year",metodo
ORDER BY anh_num,"year",metodo
;
```




# Hidrobiologicos


```{sql}
WITH a AS(
SELECT event_id,
  REGEXP_REPLACE(event_id,'^ANH([0-9]{1,3})-((F)|(MA)|(MI)|(P)|(Z))(-([ABC]))?(-Bajas)?$','\1')::int anh_num,
  REGEXP_REPLACE(event_id,'^ANH([0-9]{1,3})-((F)|(MA)|(MI)|(P)|(Z))(-([ABC]))?(-Bajas)?$','\2') grupo,
  REGEXP_REPLACE(event_id,'^ANH([0-9]{1,3})-((F)|(MA)|(MI)|(P)|(Z))(-([ABC]))?(-Bajas)?$','\9') repl,
  REGEXP_REPLACE(event_id,'^ANH[0-9]{1,3}-((F)|(MA)|(MI)|(P)|(Z))(-([ABC]))?(-Bajas)?$','\9') ='-Bajas' aguas_bajas,
  EXTRACT(YEAR FROM TO_DATE(event_date,'YYYY-MM-DD')) año
FROM raw_dwc.hidrobiologico_event
)
SELECT anh_num, grupo, año, ARRAY_AGG(repl ORDER BY repl), ARRAY_AGG(repl ORDER BY repl) FILTER (WHERE aguas_bajas)
FROM a
GROUP BY anh_num, grupo, año
ORDER BY anh_num, grupo, año
```
## Fitoplancton

```{sql}
WITH a AS(
SELECT event_id,
  REGEXP_REPLACE(event_id,'^ANH([0-9]{1,3})-((F)|(MA)|(MI)|(P)|(Z))(-([ABC]))?(-Bajas)?$','\1')::int anh_num,
  REGEXP_REPLACE(event_id,'^ANH([0-9]{1,3})-((F)|(MA)|(MI)|(P)|(Z))(-([ABC]))?(-Bajas)?$','\2') grupo,
  REGEXP_REPLACE(event_id,'^ANH([0-9]{1,3})-((F)|(MA)|(MI)|(P)|(Z))(-([ABC]))?(-Bajas)?$','\9') repl,
  REGEXP_REPLACE(event_id,'^ANH[0-9]{1,3}-((F)|(MA)|(MI)|(P)|(Z))(-([ABC]))?(-Bajas)?$','\9') ='-Bajas' aguas_bajas,
  EXTRACT(YEAR FROM TO_DATE(event_date,'YYYY-MM-DD')) año
FROM raw_dwc.hidrobiologico_event
)
SELECT anh_num, grupo, año, ARRAY_AGG(repl ORDER BY repl), ARRAY_AGG(repl ORDER BY repl) FILTER (WHERE aguas_bajas)
FROM a
WHERE grupo='F'
GROUP BY anh_num, grupo, año
ORDER BY anh_num, grupo, año
```
## Macrofitas

```{sql}
WITH a AS(
SELECT event_id,
  REGEXP_REPLACE(event_id,'^ANH([0-9]{1,3})-((F)|(MA)|(MI)|(P)|(Z))(-([ABC]))?(-Bajas)?$','\1')::int anh_num,
  REGEXP_REPLACE(event_id,'^ANH([0-9]{1,3})-((F)|(MA)|(MI)|(P)|(Z))(-([ABC]))?(-Bajas)?$','\2') grupo,
  REGEXP_REPLACE(event_id,'^ANH([0-9]{1,3})-((F)|(MA)|(MI)|(P)|(Z))(-([ABC]))?(-Bajas)?$','\9') repl,
  REGEXP_REPLACE(event_id,'^ANH[0-9]{1,3}-((F)|(MA)|(MI)|(P)|(Z))(-([ABC]))?(-Bajas)?$','\9') ='-Bajas' aguas_bajas,
  EXTRACT(YEAR FROM TO_DATE(event_date,'YYYY-MM-DD')) año
FROM raw_dwc.hidrobiologico_event
)
SELECT anh_num, grupo, año, ARRAY_AGG(repl ORDER BY repl), ARRAY_AGG(repl ORDER BY repl) FILTER (WHERE aguas_bajas)
FROM a
WHERE grupo='MA'
GROUP BY anh_num, grupo, año
ORDER BY anh_num, grupo, año
```

## Macroinvertebrados

```{sql}
WITH a AS(
SELECT event_id,
  REGEXP_REPLACE(event_id,'^ANH([0-9]{1,3})-((F)|(MA)|(MI)|(P)|(Z))(-([ABC]))?(-Bajas)?$','\1')::int anh_num,
  REGEXP_REPLACE(event_id,'^ANH([0-9]{1,3})-((F)|(MA)|(MI)|(P)|(Z))(-([ABC]))?(-Bajas)?$','\2') grupo,
  REGEXP_REPLACE(event_id,'^ANH([0-9]{1,3})-((F)|(MA)|(MI)|(P)|(Z))(-([ABC]))?(-Bajas)?$','\9') repl,
  REGEXP_REPLACE(event_id,'^ANH[0-9]{1,3}-((F)|(MA)|(MI)|(P)|(Z))(-([ABC]))?(-Bajas)?$','\9') ='-Bajas' aguas_bajas,
  EXTRACT(YEAR FROM TO_DATE(event_date,'YYYY-MM-DD')) año
FROM raw_dwc.hidrobiologico_event
)
SELECT anh_num, grupo, año, ARRAY_AGG(repl ORDER BY repl), ARRAY_AGG(repl ORDER BY repl) FILTER (WHERE aguas_bajas)
FROM a
WHERE grupo='MI'
GROUP BY anh_num, grupo, año
ORDER BY anh_num, grupo, año
```

## Perifiton

```{sql}
WITH a AS(
SELECT event_id,
  REGEXP_REPLACE(event_id,'^ANH([0-9]{1,3})-((F)|(MA)|(MI)|(P)|(Z))(-([ABC]))?(-Bajas)?$','\1')::int anh_num,
  REGEXP_REPLACE(event_id,'^ANH([0-9]{1,3})-((F)|(MA)|(MI)|(P)|(Z))(-([ABC]))?(-Bajas)?$','\2') grupo,
  REGEXP_REPLACE(event_id,'^ANH([0-9]{1,3})-((F)|(MA)|(MI)|(P)|(Z))(-([ABC]))?(-Bajas)?$','\9') repl,
  REGEXP_REPLACE(event_id,'^ANH[0-9]{1,3}-((F)|(MA)|(MI)|(P)|(Z))(-([ABC]))?(-Bajas)?$','\9') ='-Bajas' aguas_bajas,
  EXTRACT(YEAR FROM TO_DATE(event_date,'YYYY-MM-DD')) año
FROM raw_dwc.hidrobiologico_event
)
SELECT anh_num, grupo, año, ARRAY_AGG(repl ORDER BY repl), ARRAY_AGG(repl ORDER BY repl) FILTER (WHERE aguas_bajas)
FROM a
WHERE grupo='P'
GROUP BY anh_num, grupo, año
ORDER BY anh_num, grupo, año
```

## Zooplancton

```{sql}
WITH a AS(
SELECT event_id,
  REGEXP_REPLACE(event_id,'^ANH([0-9]{1,3})-((F)|(MA)|(MI)|(P)|(Z))(-([ABC]))?(-Bajas)?$','\1')::int anh_num,
  REGEXP_REPLACE(event_id,'^ANH([0-9]{1,3})-((F)|(MA)|(MI)|(P)|(Z))(-([ABC]))?(-Bajas)?$','\2') grupo,
  REGEXP_REPLACE(event_id,'^ANH([0-9]{1,3})-((F)|(MA)|(MI)|(P)|(Z))(-([ABC]))?(-Bajas)?$','\9') repl,
  REGEXP_REPLACE(event_id,'^ANH[0-9]{1,3}-((F)|(MA)|(MI)|(P)|(Z))(-([ABC]))?(-Bajas)?$','\9') ='-Bajas' aguas_bajas,
  EXTRACT(YEAR FROM TO_DATE(event_date,'YYYY-MM-DD')) año
FROM raw_dwc.hidrobiologico_event
)
SELECT anh_num, grupo, año, ARRAY_AGG(repl ORDER BY repl), ARRAY_AGG(repl ORDER BY repl) FILTER (WHERE aguas_bajas)
FROM a
WHERE grupo='Z'
GROUP BY anh_num, grupo, año
ORDER BY anh_num, grupo, año
```

# Hormigas

```{sql}
WITH a AS(
SELECT event_id,
 REGEXP_REPLACE(event_id,'^ANH_([0-9]{1,3})_((Captura manual)|(Pitfall)|(Trampa de caída atún)|(Winkler))([0-9]{1,2})_(202[12])-[0-9][0-9]-[0-9][0-9](/202[12]-[0-9][0-9]-[0-9][0-9])?','\1')::int anh_num,
 REGEXP_REPLACE(event_id,'^ANH_([0-9]{1,3})_((Captura manual)|(Pitfall)|(Trampa de caída atún)|(Winkler))([0-9]{1,2})_(202[12])-[0-9][0-9]-[0-9][0-9](/202[12]-[0-9][0-9]-[0-9][0-9])?','\2') metodo,
 REGEXP_REPLACE(event_id,'^ANH_([0-9]{1,3})_((Captura manual)|(Pitfall)|(Trampa de caída atún)|(Winkler))([0-9]{1,2})_(202[12])-[0-9][0-9]-[0-9][0-9](/202[12]-[0-9][0-9]-[0-9][0-9])?','\7')::int repli,
 REGEXP_REPLACE(event_id,'^ANH_([0-9]{1,3})_((Captura manual)|(Pitfall)|(Trampa de caída atún)|(Winkler))([0-9]{1,2})_(202[12])-[0-9][0-9]-[0-9][0-9](/202[12]-[0-9][0-9]-[0-9][0-9])?','\8') año
FROM raw_dwc.hormigas_event
)
SELECT anh_num, año, metodo, ARRAY_AGG(repli ORDER BY repli) repli, count(*)
FROM a
GROUP BY anh_num, año, metodo
ORDER BY anh_num, año, metodo
;
```
```{sql}
WITH a AS(
SELECT event_id,
 REGEXP_REPLACE(event_id,'^ANH_([0-9]{1,3})_((Captura manual)|(Pitfall)|(Trampa de caída atún)|(Winkler))([0-9]{1,2})_(202[12])-[0-9][0-9]-[0-9][0-9](/202[12]-[0-9][0-9]-[0-9][0-9])?','\1')::int anh_num,
 REGEXP_REPLACE(event_id,'^ANH_([0-9]{1,3})_((Captura manual)|(Pitfall)|(Trampa de caída atún)|(Winkler))([0-9]{1,2})_(202[12])-[0-9][0-9]-[0-9][0-9](/202[12]-[0-9][0-9]-[0-9][0-9])?','\2') metodo,
 REGEXP_REPLACE(event_id,'^ANH_([0-9]{1,3})_((Captura manual)|(Pitfall)|(Trampa de caída atún)|(Winkler))([0-9]{1,2})_(202[12])-[0-9][0-9]-[0-9][0-9](/202[12]-[0-9][0-9]-[0-9][0-9])?','\7')::int repli,
 REGEXP_REPLACE(event_id,'^ANH_([0-9]{1,3})_((Captura manual)|(Pitfall)|(Trampa de caída atún)|(Winkler))([0-9]{1,2})_(202[12])-[0-9][0-9]-[0-9][0-9](/202[12]-[0-9][0-9]-[0-9][0-9])?','\8') año
FROM raw_dwc.hormigas_event
)
SELECT anh_num, año, ARRAY_AGG(DISTINCT metodo ORDER BY metodo),  count(*)
FROM a
GROUP BY anh_num, año
ORDER BY anh_num,año
;
```

# Colémbolos

```{sql}
WITH a AS(
SELECT event_id,
  REGEXP_REPLACE(event_id, '^ANH_([0-9]{1,3})_((Pitfall)|(Berlese))([0-9])_(202[12])-[0-9]{1,2}-[0-9]{1,2}(/202[12]-[0-9]{1,2}-[0-9]{1,2})?$', '\1')::int anh_num,
  REGEXP_REPLACE(event_id, '^ANH_([0-9]{1,3})_((Pitfall)|(Berlese))([0-9])_(202[12])-[0-9]{1,2}-[0-9]{1,2}(/202[12]-[0-9]{1,2}-[0-9]{1,2})?$', '\2') metodo,
  REGEXP_REPLACE(event_id, '^ANH_([0-9]{1,3})_((Pitfall)|(Berlese))([0-9])_(202[12])-[0-9]{1,2}-[0-9]{1,2}(/202[12]-[0-9]{1,2}-[0-9]{1,2})?$', '\5')::int repli,
  REGEXP_REPLACE(event_id, '^ANH_([0-9]{1,3})_((Pitfall)|(Berlese))([0-9])_(202[12])-[0-9]{1,2}-[0-9]{1,2}(/202[12]-[0-9]{1,2}-[0-9]{1,2})?$', '\6') año
FROM raw_dwc.collembolos_event
)
SELECT anh_num, año, ARRAY_AGG(DISTINCT metodo ORDER BY metodo),  count(*)
FROM a
GROUP BY anh_num, año
;

```

```{sql}
WITH a AS(
SELECT event_id,
  REGEXP_REPLACE(event_id, '^ANH_([0-9]{1,3})_((Pitfall)|(Berlese))([0-9])_(202[12])-[0-9]{1,2}-[0-9]{1,2}(/202[12]-[0-9]{1,2}-[0-9]{1,2})?$', '\1')::int anh_num,
  REGEXP_REPLACE(event_id, '^ANH_([0-9]{1,3})_((Pitfall)|(Berlese))([0-9])_(202[12])-[0-9]{1,2}-[0-9]{1,2}(/202[12]-[0-9]{1,2}-[0-9]{1,2})?$', '\2') metodo,
  REGEXP_REPLACE(event_id, '^ANH_([0-9]{1,3})_((Pitfall)|(Berlese))([0-9])_(202[12])-[0-9]{1,2}-[0-9]{1,2}(/202[12]-[0-9]{1,2}-[0-9]{1,2})?$', '\5')::int repli,
  REGEXP_REPLACE(event_id, '^ANH_([0-9]{1,3})_((Pitfall)|(Berlese))([0-9])_(202[12])-[0-9]{1,2}-[0-9]{1,2}(/202[12]-[0-9]{1,2}-[0-9]{1,2})?$', '\6') año
FROM raw_dwc.collembolos_event
)
SELECT anh_num, año,metodo, ARRAY_AGG(DISTINCT repli ORDER BY repli) repli,  count(*)
FROM a
GROUP BY anh_num, año, metodo
;

```

# Herpetos

```{sql}
WITH a AS(
SELECT event_id
FROM raw_dwc.anfibios_event
UNION
SELECT occurrence_id
FROM raw_dwc.reptiles_event
),b AS(
SELECT event_id,
  REGEXP_REPLACE(event_id,'^ANH_([0-9]{1,3})_Herp_T([0-9])_([DN])(_TE2)?$','\1')::int anh_num,
  REGEXP_REPLACE(event_id,'^ANH_([0-9]{1,3})_Herp_T([0-9])_([DN])(_TE2)?$','\2')::int repli,
  REGEXP_REPLACE(event_id,'^ANH_([0-9]{1,3})_Herp_T([0-9])_([DN])(_TE2)?$','\3') jornada,
  CASE
    WHEN REGEXP_REPLACE(event_id,'^ANH_([0-9]{1,3})_Herp_T([0-9])_([DN])(_TE2)?$','\4')='_TE2' THEN 2022
    ELSE 2021
  END año
FROM a
)
SELECT anh_num, año,ARRAY_AGG(DISTINCT repli||'('||jornada||')') repli,  count(*)
FROM b
GROUP BY anh_num, año
;
```


# Peces

```{sql}
WITH a AS(
SELECT occurrence_id event_id,
  REGEXP_REPLACE(occurrence_id,'^ANH_([0-9]{1,3})_([ARET])_([DC])(_T2)?$','\1')::int anh_num,
  REGEXP_REPLACE(occurrence_id,'^ANH_([0-9]{1,3})_([ARET])_([DC])(_T2)?$','\2') metodo,
  REGEXP_REPLACE(occurrence_id,'^ANH_([0-9]{1,3})_([ARET])_([DC])(_T2)?$','\3') jornada,
  CASE 
   WHEN REGEXP_REPLACE(occurrence_id,'^ANH_([0-9]{1,3})_([ARET])_([DC])(_T2)?$','\4')='_T2' THEN 2022
   ELSE 2021
  END año
FROM raw_dwc.peces_event
)
SELECT anh_num,metodo,año,ARRAY_AGG(jornada ORDER BY jornada),count(*)
FROM a
GROUP BY anh_num, metodo, año
ORDER BY anh_num,año, metodo
```

```{sql}
WITH a AS(
SELECT occurrence_id event_id,
  REGEXP_REPLACE(occurrence_id,'^ANH_([0-9]{1,3})_([ARET])_([DC])(_T2)?$','\1')::int anh_num,
  REGEXP_REPLACE(occurrence_id,'^ANH_([0-9]{1,3})_([ARET])_([DC])(_T2)?$','\2') metodo,
  REGEXP_REPLACE(occurrence_id,'^ANH_([0-9]{1,3})_([ARET])_([DC])(_T2)?$','\3') jornada,
  CASE 
   WHEN REGEXP_REPLACE(occurrence_id,'^ANH_([0-9]{1,3})_([ARET])_([DC])(_T2)?$','\4')='_T2' THEN 2022
   ELSE 2021
  END año
FROM raw_dwc.peces_event
)
SELECT anh_num,año,ARRAY_AGG(DISTINCT metodo ORDER BY metodo) metodo, ARRAY_AGG(jornada ORDER BY jornada) jornada,count(*)
FROM a
GROUP BY anh_num, año
ORDER BY anh_num,año
```


# Aves

```{sql}
SELECT occurrence_id event_id,sampling_protocol
FROM raw_dwc.aves_event
WHERE occurrence_id !~'^ANH_[0-9]{1,3}_A(_(P[123]))?_R[0-9]{1,2}_T[12]'
```

```{sql}
WITH a AS(
SELECT occurrence_id event_id,
  REGEXP_REPLACE(occurrence_id,'^ANH_([0-9]{1,3})_A(_(P[123]))?_R([0-9]{1,2})_(T[12])','\1')::int anh_num,
  CASE 
    WHEN
      REGEXP_REPLACE(occurrence_id,'^ANH_([0-9]{1,3})_A(_(P[123]))?_R([0-9]{1,2})_(T[12])','\2')='' THEN 'red'
    ELSE 'punto_fijo'
  END metodo,
  REGEXP_REPLACE(occurrence_id,'^ANH_([0-9]{1,3})_A(_(P[123]))?_R([0-9]{1,2})_(T[12])','\3') punto,
  REGEXP_REPLACE(occurrence_id,'^ANH_([0-9]{1,3})_A(_(P[123]))?_R([0-9]{1,2})_(T[12])','\4')::int repli,
  REGEXP_REPLACE(occurrence_id,'^ANH_([0-9]{1,3})_A(_(P[123]))?_R([0-9]{1,2})_(T[12])','\5') tempo
FROM raw_dwc.aves_event
WHERE occurrence_id ~'^ANH_([0-9]{1,3})_A(_P[123])?_R([0-9]{1,2})_(T[12])$'
)
SELECT anh_num, metodo, tempo, ARRAY_AGG(CASE WHEN metodo='red' THEN repli::text ELSE punto||'R'||repli END ORDER BY punto,repli), count(*)
FROM a
GROUP BY anh_num, metodo, tempo
ORDER BY anh_num, tempo, metodo
```

# Mamiferos


Event_id que no siguen el formato general:
```{sql}
WITH a AS(
SELECT event_id,sampling_protocol,event_id !~ '^ANH_[0-9]{1,3}_M_[RS][0-9]{1,3}(_T2)?$' regex_f
FROM raw_dwc.mamiferos_event
)
SELECT sampling_protocol, regex_f, count(*)
FROM a 
GROUP BY sampling_protocol, regex_f
--WHERE event_id !~ '^ANH_[0-9]{1,3}_M_[RS][0-9]{1,3}(_T2)?$'
```


Event_id que no siguen el formato general:
```{sql}

SELECT event_id,sampling_protocol,event_id !~ '^ANH_[0-9]{1,3}_M_[RS][0-9]{1,3}(_T2)?$' regex_f
FROM raw_dwc.mamiferos_event
WHERE event_id !~ '^ANH_[0-9]{1,3}_M_[RS][0-9]{1,3}(_T2)?$'
;
```


```{sql}
WITH A as(
SELECT event_id, sampling_protocol,
  REGEXP_REPLACE(event_id, '^ANH_([0-9]{1,3})_M_([RS])([0-9]{1,3})(_T2)?$', '\1')::int anh_num,
  REGEXP_REPLACE(event_id, '^ANH_([0-9]{1,3})_M_([RS])([0-9]{1,3})(_T2)?$', '\2') metodo,
  REGEXP_REPLACE(event_id, '^ANH_([0-9]{1,3})_M_([RS])([0-9]{1,3})(_T2)?$', '\3')::int repli,
  CASE
    WHEN REGEXP_REPLACE(event_id, '^ANH_([0-9]{1,3})_M_([RS])([0-9]{1,3})(_T2)?$', '\4') ='_T2' THEN 2022
    ELSE 2021
  END tempo
FROM raw_dwc.mamiferos_event
WHERE event_id ~ '^ANH_([0-9]{1,3})_M_([RS])([0-9]{1,3})(_T2)?$'
)
SELECT metodo, sampling_protocol, count(*)
FROM a
GROUP BY metodo, sampling_protocol
ORDER BY metodo, sampling_protocol
;
```

```{sql}
WITH A as(
SELECT event_id,
  REGEXP_REPLACE(event_id, '^ANH_([0-9]{1,3})_M_([RS])([0-9]{1,3})(_T2)?$', '\1')::int anh_num,
  CASE
    WHEN REGEXP_REPLACE(event_id,
'^ANH_([0-9]{1,3})_M_([RS])([0-9]{1,3})(_T2)?$', '\2')='R' THEN 'R. niebla'
    ELSE 'T. Sherman' 
  END metodo,
  REGEXP_REPLACE(event_id, '^ANH_([0-9]{1,3})_M_([RS])([0-9]{1,3})(_T2)?$', '\3')::int repli,
  CASE
    WHEN REGEXP_REPLACE(event_id, '^ANH_([0-9]{1,3})_M_([RS])([0-9]{1,3})(_T2)?$', '\4') ='_T2' THEN 2022
    ELSE 2021
  END tempo
FROM raw_dwc.mamiferos_event
WHERE event_id ~ '^ANH_([0-9]{1,3})_M_([RS])([0-9]{1,3})(_T2)?$'
)
SELECT anh_num, ARRAY_AGG(DISTINCT tempo ORDER BY tempo), ARRAY_AGG(DISTINCT metodo), count(*)
FROM a
GROUP BY anh_num
ORDER BY anh_num
;
```

\tiny 

```{sql}
WITH A as(
SELECT event_id,
  REGEXP_REPLACE(event_id, '^ANH_([0-9]{1,3})_M_([RS])([0-9]{1,3})(_T2)?$', '\1')::int anh_num,
  CASE
    WHEN REGEXP_REPLACE(event_id,
'^ANH_([0-9]{1,3})_M_([RS])([0-9]{1,3})(_T2)?$', '\2')='R' THEN 'R. niebla'
    ELSE 'T. Sherman' 
  END metodo,
  REGEXP_REPLACE(event_id, '^ANH_([0-9]{1,3})_M_([RS])([0-9]{1,3})(_T2)?$', '\3')::int repli,
  CASE
    WHEN REGEXP_REPLACE(event_id, '^ANH_([0-9]{1,3})_M_([RS])([0-9]{1,3})(_T2)?$', '\4') ='_T2' THEN 2022
    ELSE 2021
  END tempo
FROM raw_dwc.mamiferos_event
WHERE event_id ~ '^ANH_([0-9]{1,3})_M_([RS])([0-9]{1,3})(_T2)?$'
)
SELECT anh_num, tempo, metodo, ARRAY_AGG(repli ORDER BY repli) repli
FROM a
GROUP BY anh_num, tempo, metodo
ORDER BY anh_num, tempo, metodo
;
```

\normalsize

```{sql}
WITH A as(
SELECT event_id,
  REGEXP_REPLACE(event_id, '^ANH_([0-9]{1,3})_M_([RS])([0-9]{1,3})(_T2)?$', '\1')::int anh_num,
  CASE
    WHEN REGEXP_REPLACE(event_id,
'^ANH_([0-9]{1,3})_M_([RS])([0-9]{1,3})(_T2)?$', '\2')='R' THEN 'R. niebla'
    ELSE 'T. Sherman' 
  END metodo,
  REGEXP_REPLACE(event_id, '^ANH_([0-9]{1,3})_M_([RS])([0-9]{1,3})(_T2)?$', '\3')::int repli,
  CASE
    WHEN REGEXP_REPLACE(event_id, '^ANH_([0-9]{1,3})_M_([RS])([0-9]{1,3})(_T2)?$', '\4') ='_T2' THEN 2022
    ELSE 2021
  END tempo
FROM raw_dwc.mamiferos_event
WHERE event_id ~ '^ANH_([0-9]{1,3})_M_([RS])([0-9]{1,3})(_T2)?$'
)
SELECT anh_num, tempo, metodo, count(*)
FROM a
GROUP BY anh_num, tempo, metodo
ORDER BY anh_num, tempo, metodo
;
```